name: astrodsb
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - termcolor
  - easydict
  - ipdb
  - pytorch>=2.1
  - torchvision
  - pytorch-cuda=11.8
  - tqdm
  - scikit-learn
  - imageio
  - matplotlib
  - tensorboard
  - torchmetrics=0.9.3
  - pip
  - pip:
    - prefetch_generator
    - colored-traceback
    - torch-ema
    - gdown==4.6.0
    - clean-fid==0.1.35
    - rich
    - lmdb
    - wandb
